Form
Chamber6821/kosox-web pull request #79
Opened 2024-09-19 18:52 UTC by alteropt

2024-09-20 18:22 UTC, Chamber6821 commented on public/css/classes.css
Лучше описывать новые компоненты используя inline style, styled components или tailwind. У нас на проекте доступен только inline style

2024-09-20 18:22 UTC, Chamber6821 commented on public/index.html
> +  <link rel="stylesheet" href="/css/classes.css">
Все что лежит в папке public - неприкасаемое легаси. Лучше расширить код в src и л возможности не трогать public

2024-09-20 18:24 UTC, Chamber6821 commented
Я отметил только некоторые изменения. Ответь по ним и сделай так, что бы diff твоего PR был не более 500 зелёных строк и красных строк (по отдельности)

2024-09-20 18:27 UTC, alteropt commented on public/fonts/SansationBold.ttf
в дизайне новый шрифт указан

2024-09-20 18:27 UTC, alteropt commented on src/App.jsx
> +  console.log(process.env.REACT_APP_API_BASE)
я не добавлял ни одного

2024-09-20 18:27 UTC, alteropt commented on src/components/Form.jsx
> +        <input tabindex={2} placeholder='НАЗВАНИЕ КОМПАНИИ' type='text' name='company' />
из дизайна взято

2024-09-20 18:28 UTC, alteropt commented on public/index.html
> +  <link rel="stylesheet" href="/css/classes.css">
хорошо

2024-09-20 18:29 UTC, alteropt commented
а где мне убирать строки? я просто за все эти изменения трогал только то, что нужно(реформатировать что-то и тп)
отпиши по каким файлам мне убирать изменения и как это сделать без вреда

2024-09-20 19:03 UTC, Chamber6821 commented
Вот переформатирование - это то, что не нужно

2024-09-21 11:07 UTC, Chamber6821 commented on src/App.jsx
> +  console.log(process.env.REACT_APP_API_BASE)
Я тебе буквально строчку прокомментировал, в которой отладочный лог `console.log(...)`

2024-09-21 11:09 UTC, Chamber6821 commented on public/css/bootstrap.css
Этот файл - это библиотека, предыдущий разраб зачем-то скопировал ее код в проект. Этот файл не стоит изменять, лучше добавить своих стилей поверх

2024-09-21 11:10 UTC, Chamber6821 commented on public/css/style.css
> +  padding-right: 65px !important;
Почему important?

2024-09-21 11:12 UTC, Chamber6821 commented on public/css/style.css
Лучше описывать новые компоненты используя inline style, styled components или tailwind. У нас на проекте доступен только inline style

2024-09-26 16:52 UTC, Chamber6821 commented
Я исправил проблему с постоянно меняющимся `yarn.lock` в #82. Обновись до последнего мастера и откати `yarn.lock` в исходное состояние

2024-09-26 17:31 UTC, alteropt commented on public/css/style.css
> +  padding-right: 65px !important;
не помню, там где-то в верстке возможно в инлайне было написано, поэтому перебивать нужно было

2024-09-26 17:32 UTC, alteropt commented
так, то есть мне это сделать и могу продолжать нормально разработку?
и вопрос, как это сделать?)

2024-09-26 17:44 UTC, Chamber6821 commented
1. Ты и до этого мог работать. С гитом не надо ждать других, только если вы не меняете одну и туже часть проекта.
2. Как сделать что?

2024-09-26 18:20 UTC, alteropt commented
yarn lock откатить

2024-09-27 16:24 UTC, alteropt commented
как откатить yarn lock? и есть какой-то четкий алгоритм команд, который мне прописывать после изменений?

2024-09-27 21:59 UTC, Chamber6821 commented
https://www.freecodecamp.org/news/git-revert-file-reverting-a-file-to-a-previous-commit/

2024-10-01 15:49 UTC, alteropt commented on public/css/classes.css
то есть мне сейчас взять все новые стили, что прописал, и перенести в inline? или это на будущее?

2024-10-01 15:49 UTC, alteropt commented on src/App.jsx
> +  console.log(process.env.REACT_APP_API_BASE)
исправил

2024-10-01 15:51 UTC, alteropt commented
ну по шрифту в целом я отписал, что в дизайне новый
переносить в inline все стили мне как будто слишком долго?
отладочные логи исправил
сейчас уберу из public изменения и по факту все?

2024-10-01 15:53 UTC, Chamber6821 commented
Исправляй остальное, а там посмотрим

2024-10-01 15:54 UTC, alteropt commented
ну тогда исправил, получается

2024-10-01 15:55 UTC, alteropt commented
в public я же менял только classes.css и style.css, но его назад я уже не откачу, ибо нужно все заново переписывать

2024-10-01 15:58 UTC, Chamber6821 commented on public/css/bootstrap.css
@alteropt

2024-10-01 15:59 UTC, Chamber6821 commented on public/css/classes.css
Сейчас

2024-10-01 16:00 UTC, Chamber6821 commented on public/css/style.css
@alteropt

2024-10-01 16:00 UTC, alteropt commented on public/css/bootstrap.css
а я его разве трогал?

2024-10-01 16:01 UTC, alteropt commented on public/css/bootstrap.css
сейчас историю посмотрю

2024-10-01 16:01 UTC, Chamber6821 commented on public/css/style.css
> +  padding-right: 65px !important;
Такого не должно быть. Лучше исправить стили там, чем городить костыли здесь

2024-10-01 16:03 UTC, alteropt commented on public/css/bootstrap.css
а, ну я же просто изменил шрифты базовые и толщину дефолтную для элементов
она же все равно изменилась для сайта

2024-10-01 16:04 UTC, Chamber6821 commented on public/css/style.css
А, ещё есть CSS в виде модулей, как `Form.css` который ты ужалил

2024-10-01 16:05 UTC, alteropt commented on public/css/classes.css
но это же много времени потратить нужно
учитывая, что некоторые стили я добавлял в style уже в существующие классы. а стилей прилично

2024-10-01 16:06 UTC, Chamber6821 commented on public/css/bootstrap.css
Никого не волнует лишняя расходуемая память. Bootstrap - это отдельная цельная библиотека, код которой не должен меняться. Лучше переписывать ее части по своему и в итоге вообще выкинуть ее

2024-10-01 16:07 UTC, alteropt commented on public/css/style.css
ну это же нельзя даже назвать модулями)) там пару классов, которые не используются даже
тем более форма изменилась по дизайну

2024-10-01 16:07 UTC, Chamber6821 commented on public/css/classes.css
Ещё есть CSS в виде модулей, как `Form.css` который ты удалил. Такой вид предпочтительнее, чем inline styles

2024-10-01 16:09 UTC, Chamber6821 commented on public/css/style.css
Модулем можно назвать что угодно, что не зависит от окружения. То что функционал модуля не используется - это другой вопрос

2024-10-01 16:10 UTC, alteropt commented on public/css/classes.css
я же все равно не найду стили, которые я добавил в уже существующие классы. ну как, найду, но времени это займет прилично

2024-10-01 16:11 UTC, alteropt commented on public/css/classes.css
и почему просто нельзя изменить style.css

2024-10-01 16:11 UTC, alteropt commented on public/css/classes.css
он в целом не должен лежать в public, учитывая, что сайт не реакт

2024-10-01 16:15 UTC, alteropt commented on public/css/classes.css
я сделаю
но все равно можешь объяснить, почему убирать стили из style можно, а добавлять нет? и что мне делать со стилями, которые я добавлял уже в существующие классы? я же не переопределю их

2024-10-01 16:40 UTC, Chamber6821 commented on public/css/classes.css
Потому что общий файл стилей - это плохой решение для среднего и большого проекта. Сложно отследить как в совокупности стили действуют на код не добавляя убогих префиксов, что в итоге приводит нас к модульности. Верстальщик изначально ебанул портянку стилей, а выбрасывать их все за раз - очень долго. Поэтому разумно в новом коде отказываться от использования исходных стилей. По-прводу новых стилей: если нужно изменить стиль из style.css, то лучше переписать фрагмент на более мелкие компоненты копируя стили из style.css, с внесением необходимых изменений

2024-10-01 16:42 UTC, Chamber6821 commented on public/css/bootstrap.css
Почему ты так решил?

2024-10-01 16:48 UTC, alteropt commented on public/css/classes.css
то есть изменяемые стили классов я просто выношу в отдельный модуль?

2024-10-01 16:51 UTC, Chamber6821 commented on public/css/classes.css
В отдельные модули. Каждому компоненту по модулю

2024-10-01 16:53 UTC, alteropt commented on public/css/classes.css
ок

2024-10-01 16:53 UTC, alteropt commented on public/css/classes.css
стрктуру папок и файлов могу поменять, чтобы это выглядело по-человечески?

2024-10-01 16:55 UTC, Chamber6821 commented on public/css/classes.css
Существующий код перемещать нельзя, новый код можешь складывать например в папку components

2024-10-01 17:15 UTC, Chamber6821 commented
В описании PR напиши какие Issue он исправляет по шаблону: Fixes #issue-number

2024-10-01 17:21 UTC, alteropt commented on public/css/bootstrap.css
нет, ты прав. прошу прощения, виноват
откачу значит bootstrap

2024-10-02 04:26 UTC, alteropt commented on public/css/classes.css
![Снимок экрана (198)](https://github.com/user-attachments/assets/6fbfc898-956b-4ad1-af0d-2f7445834b8c)
что я делаю с подобными изменениями
@Chamber6821

2024-10-02 04:29 UTC, Chamber6821 commented
Нет, каждое isuue должно быть на отдельной строчке

2024-10-02 04:33 UTC, Chamber6821 commented on public/css/classes.css
@alteropt лучше перенеси изменённые стили внутрь компонента, через модельный CSS

2024-10-02 04:35 UTC, Chamber6821 commented
Это необходимо для автоматического связывания PR с Issues, что бы при принятии этого PR, решаемые им Issues автоматически закрылись

2024-10-02 16:20 UTC, alteropt commented on public/css/classes.css
@Chamber6821 смотри изменения, жду, что так, что не так

2024-10-02 17:08 UTC, Chamber6821 commented
Чекни как тут оформлено описание

https://github.com/Chamber6821/berega-map/pull/62

2024-10-02 17:50 UTC, Chamber6821 requested changes

2024-10-02 17:50 UTC, Chamber6821 commented on public/css/style.css
Когда переносишь стили в модуль, не нужно удалять их отсюда. Не стоит вообще менять этот файл

2024-10-02 17:50 UTC, Chamber6821 commented on src/components/Navbar.css
> +  width: min-content !important;
Раз уж переписываешь стили (хоть и копированиям), то избавься от этих `!important`

2024-10-02 17:50 UTC, Chamber6821 commented on src/components/Navbar.css
> +  filter: blur(0) !important;
Раз уж переписываешь стили (хоть и копированиям), то избавься от этих `!important`

2024-10-02 17:50 UTC, Chamber6821 commented on src/index.css
> +}
Не лучше ли это сделать переменной?

2024-10-02 17:50 UTC, Chamber6821 commented on src/components/Form.css
> +}
Реверт

2024-10-03 03:15 UTC, alteropt commented on src/components/Form.css
> +}
что значит реверт?

2024-10-03 03:15 UTC, alteropt commented on src/components/Form.css
> +}
"Когда переносишь стили в модуль, не нужно удалять их отсюда. Не стоит вообще менять этот файл"

я могу хотя бы сейчас оставить так, как есть? просто больше не трогаю этот файл. на проект же это никак не влияет

2024-10-03 08:42 UTC, Chamber6821 commented on src/components/Form.css
> +}
Нет, верни `style.css` в исходный вид

2024-10-03 08:43 UTC, Chamber6821 commented on src/components/Form.css
> +}
@alteropt "реверт" значит git revert, т.е. откати файл

2024-10-03 08:45 UTC, Chamber6821 commented
@alteropt чекни как тут оформлено описание

Chamber6821/berega-map#62

2024-10-03 13:32 UTC, alteropt commented on src/components/Form.css
> +}
почему это имеет такое значение? структура проекта не станет лучше, если её начальльные стили написаны через одно место

2024-10-03 14:17 UTC, alteropt commented on src/components/Form.css
> +}
например зачем мне переписывать заново каждый класс ссылок и переопределять им ховер эффект? какую масштабируемость это создает для проекта? это просто еще раз лишнее переписывание стилей, которые уже по несколько раз зачем-то в верстке прописаны

2024-10-03 17:33 UTC, Chamber6821 commented on src/components/Form.css
> +}
Ты не в тот тред пишешь. Давай продолжим обсуждение в треде выше, относящемуся непосредственно `style.css`

2024-10-03 17:33 UTC, Chamber6821 commented on src/components/Form.css
> +}
Конкретно это изменение (обрати внимание к каким строком оно относится) нужно отменить

2024-10-03 18:06 UTC, Chamber6821 commented on public/css/style.css
По поводу необходимости изменений. Струтура проекта будет улучшаться, если постепенно отказываться от плохих решений в пользу более хороших. В этом случае это постепенное улучшение заключается в написании новых стилей в отдельных модулях. Это позволяет избавится от плохих решений в горячих местах кода, которые часто меняются и не трогать то, что и так работает. Ты написал много новых стилей, которые лучше бы оформлять в модулях. Я согласен с тем, что можно переиспользовать уже существующие стили от туда, но не развивать их дальше. Так же я согласен, что можно глобально поменять для всего грифты через изменение этого файла

2024-10-04 16:45 UTC, alteropt commented on src/components/Navbar.css
> +  width: min-content !important;
убрал

2024-10-04 16:46 UTC, alteropt commented on src/components/Navbar.css
> +  filter: blur(0) !important;
здесь нужно, чтобы перебить стили слайдера

2024-10-04 16:46 UTC, alteropt commented on src/index.css
> +}
мне привычнее в данном случае использовать классы

2024-10-05 13:34 UTC, Chamber6821 commented
@alteropt читай все не решенные треды. Пока есть нерешенные треды, PR не может быть смерджен

2024-10-05 13:40 UTC, Chamber6821 commented
@alteropt ты не правильно упомянул Issue которые этот PR удовлетворяет. Читай выше

2024-10-13 15:55 UTC, Chamber6821 requested changes

2024-10-13 15:55 UTC, Chamber6821 commented on public/css/style.css
> +    background: #f00;
Почему не в виде стиля какого-нибудь компонента?

2024-10-13 15:55 UTC, Chamber6821 commented on src/components/Form.css
> +/* FORM */
По названию файла и так понятно, что эти слили относятся к форме

2024-10-13 15:55 UTC, Chamber6821 commented on src/pages/Home.jsx
> +import '../components/Form.css'
CSS файл компонента должен лежать рядом с компонентом, так же только компонент должен испортить свой файл. Тоже правило для страниц

2024-10-13 17:24 UTC, Chamber6821 commented
Шрифт говно какое-то
![image](https://github.com/user-attachments/assets/17531931-3b60-48d2-acab-6fe4e7162ca4)

2024-10-13 17:28 UTC, Chamber6821 commented
Буква k похожа на R. Надо менять

2024-10-13 17:53 UTC, Chamber6821 requested changes

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +    width: 100%;
Лишние пробелы в конце

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +    color: #FF5F31 !important;
Этот стиль уже добавлен в Home.css. Поскольку здесь он отмечен как important, стоит его удалить и тогда стили будут выбираться корректно

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +    background: #c3401b;
Стиль перебит в Home.css, можешь просто удалить его

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +    background: #c3401b;
Стиль перебит в Home.css. Можешь просто удалить его

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +    color: #FF5F31 !important;
Стиль перебит в Home.css. Можешь просто удалить его

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +    background: #c3401b;
Стиль перебит в Home.css. Можешь просто удалить его

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on public/css/style.css
> +
Пустая строка

2024-10-13 17:53 UTC, Chamber6821 commented on src/components/Home.css
> +    color: #FF5F31 !important;
Здесь не нужен important, если удалить лишние стили из style.css

2024-10-13 17:53 UTC, Chamber6821 commented on src/components/Home.css
> +    color: #FF5F31 !important;
Здесь не нужен important, если удалить лишние стили из style.css

2024-10-13 17:53 UTC, Chamber6821 commented on src/components/Navbar.css
> +  filter: blur(0) !important;
Эти стили опеределены через inline-style. Просто надо удалить их из inline и полностью перенести в CSS. Тогда important не понадобится

2024-10-13 17:53 UTC, Chamber6821 commented on src/index.css
> +}
Замени `<span class="active-color">...</span>` на компонент `Attention`, который тебе надо написать

2024-10-13 17:53 UTC, Chamber6821 commented on src/index.css
> +}
Либо напиши универсальный компонент Container, который подходит в большинстве случаей и в случае чего его можно донастроить, либо просто пропиши этот несчастный падинг там, где он нужен

2024-10-13 17:53 UTC, Chamber6821 commented on src/index.css
> +}
Пускай о ширине шрифта внутри input забодится сам input или компонент-обертка

2024-10-13 17:53 UTC, Chamber6821 commented on src/index.css
> +}
Зачни здесь подключение шрифта и с CDN, и из файлов проекта?

2024-10-13 17:57 UTC, Chamber6821 commented on public/css/style.css
> +    background: #f00;
Этот стиль перебивается из Navbar.css. Его можно просто удалить

2024-10-13 17:59 UTC, Chamber6821 commented
Странно отображаются иконки в Navbar
![image](https://github.com/user-attachments/assets/a833f56d-cccd-4a1c-9120-d0aed3913187)

2024-10-13 18:01 UTC, Chamber6821 commented
Черный текст на черном фоне. Home.jsx
![image](https://github.com/user-attachments/assets/7fc26895-9aaa-4b57-bf3f-6a7f124d9983)

2024-10-13 18:01 UTC, Chamber6821 commented
Высота блока с отзывами меняется в зависимости от выбранного отзыва
![image](https://github.com/user-attachments/assets/8161b9d4-8fb5-4475-919f-c02a845e1943)

2024-10-13 18:07 UTC, Chamber6821 commented
Форма уехала во всех местах ее использования. Нужно завернуть ее в компонент `Centered` (его тоже надо написать). Причем стили для компонента должны быть модулем (лежать в файле `Centered.module.css`). У контейнера должно быть слелующие стили:
```css
.centered {
  display: flex;
  justify-content: center;
  align-items: center;
}
```
Должна быть возможность доопределять стили контейнера, т.е. у компонента должен быть проперти `style`
![image](https://github.com/user-attachments/assets/ebb59e09-0296-4057-b506-1c32152ae399)

2024-10-13 18:09 UTC, Chamber6821 commented
`catalog/index.jsx`
Черный текст на темном фоне
![image](https://github.com/user-attachments/assets/8fd2a8b0-0734-417d-b061-ee5d1747f8f7)

2024-10-13 18:10 UTC, Chamber6821 commented
`category/index.jsx`
Черный текст на темном фоне
![image](https://github.com/user-attachments/assets/ea1044bd-4dab-4463-91fa-76d2f6e99217)

2024-10-13 18:11 UTC, Chamber6821 commented
`category/index.jsx`
Чекбоксы скукожились
![image](https://github.com/user-attachments/assets/75460fa7-e5d7-442e-9d73-587792cd5e71)

2024-10-14 08:18 UTC, alteropt commented
такой в фигме дан)

2024-10-14 08:19 UTC, alteropt commented
> Шрифт говно какое-то ![image](https://private-user-images.githubusercontent.com/60232245/376055531-17531931-3b60-48d2-acab-6fe4e7162ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTQwNTMsIm5iZiI6MTcyODg5Mzc1MywicGF0aCI6Ii82MDIzMjI0NS8zNzYwNTU1MzEtMTc1MzE5MzEtM2I2MC00OGQyLWFjYWItNmZlNGU3MTYyY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA4MTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOGY1MGI1ZGRlMjc3YzQwNTk1NTdhZjhhNWIzZGE4Yjg4MzJjOWVjMDM3ZWE2ZGU0MTI5ZjhlNmRmZDg1YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jsL9vk7O839fbb16H4rUFfRSsrN1F2kpwOq_O-nJZX8)

такой в фигме указан

2024-10-14 08:21 UTC, alteropt commented on public/css/style.css
> +    color: #FF5F31 !important;
ок

2024-10-14 08:21 UTC, alteropt commented on public/css/style.css
> +    background: #c3401b;
ок

2024-10-14 08:21 UTC, alteropt commented on public/css/style.css
> +    background: #c3401b;
ок

2024-10-14 08:21 UTC, alteropt commented on public/css/style.css
> +    color: #FF5F31 !important;
ок

2024-10-14 08:22 UTC, alteropt commented on public/css/style.css
> +    background: #c3401b;
ок

2024-10-14 08:22 UTC, alteropt commented on src/components/Home.css
> +    color: #FF5F31 !important;
ок

2024-10-14 08:23 UTC, alteropt commented on src/components/Home.css
> +    color: #FF5F31 !important;
ок

2024-10-14 08:28 UTC, alteropt commented on src/index.css
> +}
не помню уже, честно говоря. ок, исправлю

2024-10-14 08:29 UTC, alteropt commented
> Странно отображаются иконки в Navbar ![image](https://private-user-images.githubusercontent.com/60232245/376057789-a833f56d-cccd-4a1c-9120-d0aed3913187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTQwNTMsIm5iZiI6MTcyODg5Mzc1MywicGF0aCI6Ii82MDIzMjI0NS8zNzYwNTc3ODktYTgzM2Y1NmQtY2NjZC00YTFjLTkxMjAtZDBhZWQzOTEzMTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA4MTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZDVlMzM0OTZkMzI3MWY3MzE0NWY5NjM1M2E3NjAyOTU1NzEyYmViNzQ0MTUzYzY4MjQxZjRkOTIzMWMzZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D9TP0TwfmcktqXqowjUKJ938z5J4jMd9SCmqogdRmqU)

потому что они неправильно подгружаются. я последующих ветках исправил данный момент

2024-10-14 08:30 UTC, alteropt commented
цвета шрифтов не соответствуют дизайну, так как их нужно менять непосредственно в style.css
опять же там для многих элементов это задано отдельно. постараюсь исправить этот момент

2024-10-14 08:31 UTC, alteropt commented
форма написана только для главной страницы. я не смотрел ее соответствие на других

2024-10-14 08:31 UTC, alteropt commented
и на других страницах, опять же, я не смотрел отображение, так как сейчас работаю над главной

2024-10-14 08:40 UTC, Chamber6821 commented on src/index.css
> +}
Да. Хорошо. Только используй для компонентов модульный CSS, для которого генерируются уникальные названия классов

2024-10-14 08:41 UTC, Chamber6821 commented on src/index.css
> +}
Думаю стоит дополнить класс `form` и просто избавится от этой прослойки

2024-10-14 08:43 UTC, Chamber6821 commented on src/index.css
> +}
Думаю лучше оставить только CDN и удалить шрифты из проекта

2024-10-16 17:10 UTC, Chamber6821 requested changes

2024-10-16 17:19 UTC, Chamber6821 commented
@alteropt позже проверю отображение

2024-10-23 18:56 UTC, Chamber6821 commented
Карточки каталога и категории имееют темные углы

![image](https://github.com/user-attachments/assets/56c981be-4c72-4511-985c-25a41998faf1)

2024-10-23 19:00 UTC, Chamber6821 commented
Карточка товара имеет темные углы

![image](https://github.com/user-attachments/assets/90f829b8-d2cf-4e73-8a64-2b92bbe3d81d)

2024-10-24 19:41 UTC, Chamber6821 commented
@alteropt что с высотой отзывов?

2024-10-25 03:40 UTC, alteropt commented
мы так договорились, чтобы плавно изменялась высота блока в зависимости от выбранного отзыва

2024-10-25 13:00 UTC, Chamber6821 approved these changes

2024-10-25 13:01 UTC, merged