About
Chamber6821/kosox-web pull request #89
Opened 2024-10-27 06:04 UTC by alteropt

fixes #53 
fixes #52 
fixes #40 
fixes #39 
fixes #38

2024-10-28 12:48 UTC, Chamber6821 requested changes

2024-10-28 12:48 UTC, Chamber6821 commented
@alteropt следующие PR больше, чем на 200 зеленых строк я буду реджектить не проверяя

2024-10-28 13:21 UTC, alteropt commented on src/index.css
> +.cntr {
почему?

2024-10-28 13:24 UTC, alteropt commented on src/pages/catalog/Card.jsx
> +      <img src={backgroundImage} alt='bg' />
а что не так с этим alt? просто background

2024-10-28 13:25 UTC, alteropt commented on src/pages/catalog/Cards.jsx
> +          ))}
так я здесь им и пользуюсь

2024-10-28 13:25 UTC, alteropt commented on src/pages/catalog/Cards.jsx
> +  const [isAllCategories, setIsAllCategories] = useState(false)
в реакт коде если стейт это boolean обыно используется префикс is

2024-10-28 13:25 UTC, alteropt commented on src/pages/css/Home.css
> +  background: linear-gradient(rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)), url(../../../public/img/advantages/background.jpg), center / cover;
ок

2024-10-28 13:26 UTC, alteropt commented on src/pages/css/Home.css
> +.primushestva_company {
так было изначально, я лишь соблюдаю нейминг классов, что был до этого
иначе все классы нужно будет переписывать заново, не только свои

2024-10-28 13:28 UTC, alteropt commented on src/pages/Home.jsx
> +            <button className={activeTab === '13' ? 'active' : ''} onClick={event => toggleTab(event)} data--promishlenost-key='13'>Пищевая промышленность</button>
почему не нужен атрибут? я из него беру значение и связываю с определенным табом

2024-10-28 13:28 UTC, alteropt commented on src/pages/css/Home.css
> +.kotalog {
это не мой нейминг классов

2024-10-28 13:28 UTC, alteropt commented on src/pages/Home.jsx
> +  const [activeTab, setActiveTab] = useState('1')
почему?

2024-10-28 14:23 UTC, Chamber6821 commented on src/pages/catalog/Cards.jsx
> +          ))}
Ты его используешь не правильно (что привело к дублированию кода). Вот как правильно:
```ts
(isAllCategories ? categories : categories.slice(0, 6)).map(...)
```

2024-10-28 14:29 UTC, Chamber6821 commented on src/pages/catalog/Cards.jsx
> +  const [isAllCategories, setIsAllCategories] = useState(false)
Код стайл конкретного проекта приоритетнее общепринятых практик
В добавок могу сказать, что префикс `is` ничем не отличается от уже не популярных префиксов `i` для интов или `f` для флоатов, т.е. является рудиментом, который засоряет код

2024-10-28 14:32 UTC, Chamber6821 commented on src/pages/Home.jsx
> +            <button className={activeTab === '13' ? 'active' : ''} onClick={event => toggleTab(event)} data--promishlenost-key='13'>Пищевая промышленность</button>
Атрибуты для передачи даннхы нужны только когда ты пишешь на сыром JS. Вместе с реактом ты можешь легко использовать замыкания. В реакте не стоит обратно из HTML доставать данные (исключение - инпуты). Направление движения данных: React -> DOM. Использования разнообразных механизмов для управления усложняет чтение и понимание кода проекта в целом

2024-10-28 14:36 UTC, Chamber6821 commented on src/index.css
> +.cntr {
Потому что сокращения сложнее читаются в месте использования

2024-10-28 14:42 UTC, Chamber6821 commented on src/index.css
> +.btn {
Потому что сокращения сложнее читаются в месте использования. `btn` хоть и распостраненное сокращение, но это не значит, что должно быть исключение для одного него

2024-10-28 14:49 UTC, Chamber6821 commented on src/pages/Home.jsx
>            </div>
Отдельный ресурсный файл + рендер по абзацам
```json
[
  {
    "title": "Металлургия",
    "content": [
      "Металлургия — это  изучение, извлечение, переработка и производство металлов и сплавов. Этот процесс включает в себя множество этапов, начиная от добычи руды и заканчивая выпуском готовой металлической продукции. Металлургия охватывает различные направления, такие как черная (железо и его сплавы) и цветная металлургия (все остальные металлы)",
      "В металлургии важную роль играют физико-химические свойства материалов, которые позволяют лучше понять, как металлы реагируют на те или иные условия обработки. Металлургия также включает в себя разработку новых  технологий, что позволяет создавать более прочные, легкие и устойчивые к коррозии материалы.",
      "В металлургии применяются различные типы подшипников. Основными являются радиальные и радиально-упорные подшипники, которые используются в различных машинах и агрегатах, таких как конвейеры, печи, тачки и прокатные станы. В условиях высокой температуры и воздействия агрессивных сред, например, в доменных печах, предпочтение отдается подшипникам из специальных материалов, таких как керамика или высокотемпературные сплавы. Также в металлургии важную роль играют подшипники с высокой устойчивостью к загрязнениям, что обеспечивает их долговечность и минимизирует риски поломок."
    ]
  }
]
```
или отдельный JSX файл
```jsx
export const ProductionDescriptions = [
  {
    "title": "Металлургия",
    "content": [
      () => <p>Металлургия — это  изучение, извлечение, переработка и производство металлов и сплавов. Этот процесс включает в себя множество этапов, начиная от добычи руды и заканчивая выпуском готовой металлической продукции. Металлургия охватывает различные направления, такие как черная (железо и его сплавы) и цветная металлургия (все остальные металлы)</p>
    ]
  }
]
```

2024-10-28 14:51 UTC, Chamber6821 commented on src/pages/css/Home.css
> +.primushestva_company {
Если переписываешь классы из `style.css`, то нужно переназывать их в соответсвии с требованиями проекта

2024-10-28 14:51 UTC, Chamber6821 commented on src/pages/css/Home.css
> +.kotalog {
Если переписываешь классы из `style.css`, то нужно переназывать их в соответсвии с требованиями проекта

2024-10-31 19:47 UTC, alteropt commented on src/index.css
> +.cntr {
в смысле сложнее читаются? кем? .cntr или .btn тяжело прочитать и понять, что оно означает?

2024-10-31 19:49 UTC, alteropt commented on src/pages/Home.jsx
>            </div>
ок

2024-10-31 19:49 UTC, alteropt commented on src/pages/catalog/Card.jsx
> +      <img src={backgroundImage} alt='bg' />
ок

2024-10-31 19:50 UTC, alteropt commented on src/pages/catalog/Cards.jsx
> +          ))}
это неправильно
в таком случае при isAllCategories=true просто будет выводиться массив categories

2024-10-31 19:51 UTC, alteropt commented on src/pages/catalog/Cards.jsx
> +  const [isAllCategories, setIsAllCategories] = useState(false)
да, но тут никакого код стайла и нету, это первая подобная константа. почему нельзя оформить в таком привычном формате

2024-10-31 19:52 UTC, alteropt commented on src/pages/catalog/Cards.jsx
> +  const [isAllCategories, setIsAllCategories] = useState(false)
и я бы не согласился насчет сравнения is с рудиментом. это вполне логичный префикс, указывающий на boolean тип

2024-10-31 19:53 UTC, alteropt commented on src/pages/Home.jsx
> +            <button className={activeTab === '13' ? 'active' : ''} onClick={event => toggleTab(event)} data--promishlenost-key='13'>Пищевая промышленность</button>
не знаю, как это написать через замыкания. и не понимаю, где здесь усложнение читаемости кода. код максимально тривиальный

2024-10-31 19:55 UTC, alteropt commented on src/pages/css/Home.css
> +.primushestva_company {
этот класс в верстке таким и был
это в целом нелогично и противоречит бэм, если я перепишу этот класс на другое имя. тут или все классы переписывать, или оставлять так

2024-10-31 19:55 UTC, alteropt commented on src/pages/css/Home.css
> +.kotalog {
аналогично. такой класс уже был до этого

2024-10-31 22:23 UTC, Chamber6821 commented on src/pages/catalog/Cards.jsx
> +          ))}
Нет, тернарный оператор взят в скобочки. Приоритет операций другой

2024-10-31 22:26 UTC, Chamber6821 commented on src/pages/catalog/Cards.jsx
> +  const [isAllCategories, setIsAllCategories] = useState(false)
Потому что `isAllCategories` не отражает назначение этого флага. Однозначно стоит переформулировать название так, что бы оно указывало на отображение лишь части списка категорий.

Тогда почему ты не используешь `i`/`f`/`s`/`n` для всех имен переменных соответсвтвующих типов?

2024-10-31 22:27 UTC, Chamber6821 commented on src/pages/css/Home.css
> +.primushestva_company {
Соответсвено нужно переписать все классы связанные с этим классов

2024-11-01 14:04 UTC, alteropt commented on src/pages/catalog/Cards.jsx
> +          ))}
в таком случае при isAllCategories=true просто будет выводиться массив categories

2024-11-01 14:05 UTC, alteropt commented on src/pages/catalog/Cards.jsx
> +  const [isAllCategories, setIsAllCategories] = useState(false)
потому что нигде я не видел использование подобных префиксов на проектах

2024-11-01 14:05 UTC, alteropt commented on src/pages/catalog/Cards.jsx
> +  const [isAllCategories, setIsAllCategories] = useState(false)
данная формулировка указывает на отображение всех категорий - то же самое, только в обратную сторону

2024-11-01 14:06 UTC, alteropt commented on src/pages/css/Home.css
> +.primushestva_company {
моей задачей, если я не ошибаюсь, был редизайн, а не деструктуризация и перенаписание кода на чистый

2024-11-01 20:31 UTC, Chamber6821 commented
Мы поговорили с Мишей, получилось так, что тебя наебали с гитом. Проект надо заканчивать уже на похуй, поэтому просто отправляй изменения, я буду проверять только визуал и апрувить

2024-11-01 20:31 UTC, Chamber6821 approved these changes

2024-11-01 20:32 UTC, merged